### ISSUE TITLE
App To-Do List

### ISSUE THREAD

**Issue by BradHoffman96** [BradHoffman96/Heimdall#1]
- [ ] Make Provider v3 Template w/ Networking & SharedPreferences
- [ ] Build Authentication Logic
- [ ] Build Home Page (Tabbed layout?)

More to be added...
