### ISSUE TITLE
Server To-Do List

### ISSUE THREAD

**Issue by BradHoffman96** [BradHoffman96/Heimdall#2]
- [ ] Decide upon Features
- [ ] Forward and Reverse DNS Lookups
- [ ] Host discovery
- [ ] Traffic categorization
- [ ] Traffic Statistics
- [ ] Authentication
- [ ] Connect to Database (PostgreSQL?)
- [ ] Routing
- [ ] Setup Dev Server at Home
